rules:
  - id: k8s-secret-key-ref
    message: Kubernetes manifest references a Secret via secretKeyRef or secretRef.
    languages: [yaml]
    severity: INFO
    pattern-either:
      - pattern: |
          secretKeyRef:
            name: $NAME
            key: $KEY
      - pattern: |
          secretRef:
            name: $NAME
      - pattern: |
          valueFrom:
            secretKeyRef:
              ...
      - pattern: |
          envFrom:
            - secretRef:
                ...
      - pattern: |
          volumes:
            - secret:
                secretName: $NAME
